import datetime

import discord
from sqlalchemy import select, update

from pyboss.models import ScheduleRefModel
from pyboss.utils import database


async def send_embed(ctx, title, content):
    embed = discord.Embed(
        title=title,
        description=content,
        colour=0xFFA325,
        timestamp=datetime.datetime.now(),
    )
    embed.set_thumbnail(url=ctx.guild.icon_url)
    embed.set_footer(text=f"Generated by {ctx.bot.user.name}")

    await ctx.channel.send(embed=embed)


async def update_message_ref(message: discord.Message):
    """
    Update id of agenda or planning message in database
    """
    ex_message = database.execute(
        select(ScheduleRefModel).where(
            ScheduleRefModel.guild_id == message.guild.id,
            ScheduleRefModel.channel_id == message.channel.id,
        )
    ).scalar_one
    database.execute(update(ScheduleRefModel).values(message_id=message.id))
    try:
        ex_message = await message.channel.fetch_message(ex_message.id)
    except (discord.NotFound, discord.HTTPException):
        return
    await ex_message.delete()
