version: "3.9"

services:
  postgres:
    image: postgres
    container_name: PyBoss_PostgreSQL
    environment:
      - POSTGRES_DB=PyBoss
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "2345:5432"

  bot:
    container_name: PyBoss_Bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/PyBoss
    env_file:
      - .env
    environment:
      ENVIRONMENT: production
      DATABASE_URL: postgresql+psycopg2://root:root@postgres:5432/PyBoss
    depends_on:
      - postgres