from datetime import datetime

import discord
from discord.ext.commands import Cog, check, command, is_owner
from sqlalchemy import insert

from pyboss import STATIC_DIR
from pyboss.models import SuggestionModel
from pyboss.utils import database

from .utils.checkers import is_suggestion_channel


class Suggestion(Cog):
    """
    Offers commands to allow members to propose suggestions and interact with them
    """

    def __init__(self, bot):
        self.bot = bot

    @command(name="suggestions_rules", hidden=True)
    @is_owner()
    @check(is_suggestion_channel)
    async def send_suggestions_rules(self, ctx):
        """
        Send the rules for suggestion channel
        """
        await ctx.message.delete()
        with open(STATIC_DIR / "text/suggestions_rules.md", encoding="utf-8") as f:
            content = f.read()
        embed = discord.Embed(
            title="Fonctionnement des suggestions", description=content, colour=0xFF66FF
        )
        embed.set_thumbnail(url=ctx.guild.icon_url)
        embed.set_footer(
            text=f"Generated by {self.bot.user.name} | {datetime.now():%D - %H:%M}"
        )
        await ctx.send(embed=embed)

    @Cog.listener("on_message")
    async def make_suggestion(self, message):
        if is_suggestion_channel(message):
            await message.add_reaction("✅")
            await message.add_reaction("❌")

    @Cog.listener("on_raw_reaction_add")
    async def decisive_reaction(self, payload):
        """
        Send result to all users when the owner add a reaction
        """
        channel = self.bot.get_channel(payload.channel_id)
        message = await channel.fetch_message(payload.message_id)

        if (
            str(payload.emoji) not in ("✅", "❌")
            or not is_suggestion_channel(message)
            or not self.bot.is_owner(message.author)
        ):
            return

        accepted: bool = str(payload.emoji) == "✅"
        if accepted:
            stmt = insert(SuggestionModel).values(
                author=message.author.name, description=message.content
            )
            database.execute(stmt)
        for reaction in message.reactions:
            if str(reaction.emoji) == "✅":
                async for user in reaction.users():
                    await self.send_dm_suggestion_state(user, accepted, message)
        await self.send_dm_suggestion_state(message.author, accepted, message)

        await message.delete()

    async def send_dm_suggestion_state(self, user, accepted: bool, suggestion):
        """
        Send a message to a member who has voted to inform of the state of the reaction
        """
        citation = "\n> ".join(suggestion.content.split("\n"))

        if accepted:
            embed = discord.Embed(
                colour=0xFF22BB,
                title="Suggestion acceptée!",
                description=(
                    f"**Félicitations!** "
                    f"La suggestion de **{suggestion.author.name}** pour laquelle "
                    f"vous avez voté a été acceptée:\n> {citation} \n\n"
                    "__Note__: \n Il faut parfois attendre plusieurs jours "
                    "avant qu'elle soit effective",
                ),
            )
        else:
            embed = discord.Embed(
                colour=0xFF22BB,
                title="Suggestion refusée!",
                description=(
                    f"**Mauvaise nouvelle...** "
                    f"la suggestion de **{suggestion.author.name}** pour laquelle "
                    f"vous avez voté a été malheureusement refusée:\n> {citation}\n\n"
                ),
            )
        embed.set_thumbnail(url=STATIC_DIR / "img/alert.png")
        embed.set_footer(
            text=f"{self.bot.user.name} | This message was sent automatically"
        )
        await user.send(embed=embed)


def setup(bot):
    bot.add_cog(Suggestion(bot))
